### ISSUE TITLE
Multi-joins

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#13]
with `cdm_join_tbl()` we are able to join two tables of a `dm` which share a direct link (FK).

what if we want to join a further table from the same `dm` in a second step etc.?

A solution would be a new function, which wraps `cdm_join_tbl()` and then returns the original `dm`, but with the result of the join as an additional table. This way, there would be the possibility of adding a secondary join to this table in the pipeline.

Questions would be: 
- what will the PK of the new table be (depends probably on the type of the join and the type of the relation between the joined tables)?
- how to determine the FKs from and to the newly created table?

**Comment by krlmlr** [comment]
New operation: `cdm_flatten(dm, join = left_join)`. Always flatten the entire data model, we can remove tables beforehand with `cdm_select_tbl()`. Returns a table (in-memory or db).

The operation is well-defined iff all tables are connected and have at most one foreign table pointing to them (e.g. flights -> (planes, airports)). Don't worry about undefined behavior for now.

1. Disambiguate with #41.
1. Use `igraph::topo_sort()` to sort the tables.
1. In the resulting order, run:

    ```r
    flights %>%
      rename(tailnum = tailnum) %>%
      join(planes, by = "tailnum") %>%
      rename(faa = origin) %>%
      join(airports, by = "faa")
    ```

    Reason: We want to preserve the column name of the **primary key** but the table has to be the RHS table to preserve join semantics.
