### ISSUE TITLE
Change lifecycle to "maturing"

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#154]
- [x] Use {lifecycle}
- [x] Update pkgdown reference index
- [x] Double-check API consistency, define logic for prefixes (and suffixes)
- [x] Check column names of functions that return a data frame
- [x] Check lifecycle status of all functions, mark "questioning" if in doubt
- [x] Mark all functions with non-default lifecycle
- [x] Update README

**Comment by krlmlr** [comment]
First steps: update `_pkgdown.yml` to match desired state.

**Comment by TSchiefer** [comment]
Is there a way to mention the methods in the reference index, or can we only talk about them in the documentation of other functions or in the vignettes?

**Comment by krlmlr** [comment]
We can create help pages for the methods. See e.g. sf and https://r-spatial.github.io/sf/reference/tidyverse.html. Is it worth it?

**Comment by TSchiefer** [comment]
Surely wouldn't harm, but if we document the methods properly in other places, it might be fine too. Something like pointing out the differences to known methods is probably important (e.g. our `xxxx_join.zoomed_dm` with its `select` argument).

**Comment by krlmlr** [comment]
Yeah, let's do a help page later. Can you please open an issue?

**Comment by TSchiefer** [comment]
update of pkgdown reference index in #210 

issue of help page for methods is #209

**Comment by TSchiefer** [comment]
`decompose_table()` and `reunite_...()` will probably be replaced with functions that work within a `dm`, like `dm_separate_tbl()` and `dm_unite_tbl()`, so lifecycle should be changed accordingly

**Comment by TSchiefer** [comment]
For logic of prefixes and suffixes, see https://github.com/krlmlr/dm/pull/210#issuecomment-561586206 and following comments

**Comment by krlmlr** [comment]
On it. Thanks for preparing everything!

**Comment by TSchiefer** [comment]
Nice. 

BTW, what do you think of keeping `decompose_table()` etc. in addition to their in-`dm` implementations? They seem to be useful sometimes.

**Comment by krlmlr** [comment]
Done now.
