### ISSUE TITLE
Implement code generator for existing dm-s

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#160]
```r
cdm_nycflights() %>% dm_paste()
```

Desired output: 

```
dm(flights, planes, airports, airlines, weather) %>%
  cdm_add_pk(planes, tailnum) %>%
  cdm_add_pk(airlines, carrier) %>%
  cdm_add_pk(airports, faa) %>%
  cdm_add_fk(flights, tailnum, planes) %>%
  cdm_add_fk(flights, carrier, airlines) %>%
  cdm_add_fk(flights, origin, airports)
```

Add a `select = FALSE` option that also injects `cdm_select()` statements for the columns in the tables.

In the spirit of {datapasta}, perhaps it could move there some day?

**Comment by TSchiefer** [comment]
The first line of the desired output could potentially be problematic, if the tables are not available in the global environment under the necessary names. 

We could anyway implement it this way, but in case we don't see the respective tables we can issue a warning, that the user needs to supply the tables himself (or just always write such a message along with the output).

**Comment by krlmlr** [comment]
The generated code doesn't need to be perfect, we just assume that these objects exist (and perhaps add a comment beforehand).
