### ISSUE TITLE
Rethink application of filter

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#161]
Querying a table shouldn't apply filters. All filters are now applied right away to the respective tables (#124), applying filters to ensure integrity should be a conscious operation.

**Comment by krlmlr** [comment]
It should be possible to apply filters for a single table and then return it. What would that operation be called=

**Comment by TSchiefer** [comment]
Would `cdm_filter_to_tbl()` be too weird?

**Comment by TSchiefer** [comment]
I think I first misunderstood what you meant: you still want a function that does the same as `tbl.dm()` currently does, right?

In this case I would suggest to call it `cdm_apply_filters_to_tbl()`
