### ISSUE TITLE
Shorten description in ?cdm_disambiguate_cols

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#165]
https://github.com/krlmlr/dm/pull/158/files#r347016441

**Comment by bbecane** [comment]
I shortened the description but it seems that my suggestions did not get inserted before the PR was closed. Can we find those suggestions in the comment history / log?

**Comment by krlmlr** [comment]
I'm not sure. Do you remember the wording? It feels quicker to do it again than to hunt for the change, and the chances to find it are slim.

**Comment by bbecane** [comment]
I searched but could not find. I rephrased it again in my local copy and will push later.

**Comment by bbecane** [comment]
When two tables are joined, then is it the primary key column that is kept in the flattened table or the foreign key, or it makes no difference because they are essentially the same?

**Comment by krlmlr** [comment]
The LHS column is kept (with flattening it's always the foreign key), the RHS column is discarded. Often they have the same name.

**Comment by bbecane** [comment]
Thanks
