### ISSUE TITLE
Simplify ?cdm_enum_fk_candidates

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#167]
https://github.com/krlmlr/dm/pull/158/files#r347023515

**Comment by bbecane** [comment]
cdm_enum_fk_candidates() mentions argument 'by' but that argument is not listed as a parameter or a parameter that is inherited.

**Comment by krlmlr** [comment]
I can't find "by" in https://krlmlr.github.io/dm/reference/enum_pk_candidates.html?

**Comment by bbecane** [comment]
#' If `ref_table` does have a primary key, then, for each column of `table`, 
#' a join operation will be tried, with argument `by` matching
#' the respective column with the primary key of `ref_table`.

**Comment by TSchiefer** [comment]
...just happened to see your discussion. The `by` argument mentioned here is referring to the `join` operation, as in `left_join(table_1, table_2, by = "key")`. 

I guess the question could be if it's necessary to go into so much detail.

**Comment by bbecane** [comment]
Thank you, that was helpful.
