### ISSUE TITLE
Avoid discussing data_model component in documentation

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#170]
Originally, a `dm` consisted of a `src`, a `tables` and a `data_model` component. This is no longer true, but still occurs in the documentation in some places.

What's the best way to frame this? Perhaps something like:

- a `dm` consists of a collection of tables
- it maintains metadata for these tables: table and column names, and primary and foreign keys that link the tables
- all tables in a `dm` must be "on the same source", i.e. all must be local data frames or reside on the same database

Search for "three", "data_model", and "component" in `*.Rmd` files.

**Comment by bbecane** [comment]
draw-dm.R contains the cdm_get_data_model() function that is mentioned in some documentation

**Comment by bbecane** [comment]
Data model is referenced in some functions and code examples:

dm.R:
- Data model class
- cat_rule("Data model", col = "violet")
- tables in data_model must be a subset of tables in src
- cdm_get_data_model_pks <- function(x)

**Comment by krlmlr** [comment]
Thanks. Let's focus on documentation first.

I'm replacing the "Data model" in the printed output with "Metadata". This resolves the ambiguity with `dm` as "data model class".

**Comment by bbecane** [comment]
Is the physical location of data sources part of the metadata?

**Comment by bbecane** [comment]
I am getting an error when I try to knit the 'dm' and basic operations.rmd vignette, it seems to result from a code example:

Error in dm_from_src(src_df(pkg = "nycflights13")) : 
  could not find function "dm_from_src"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted

**Comment by bbecane** [comment]
FYI: the RStudio 2020 conference abstract mentions data_model.
