### ISSUE TITLE
How to extract the currently zoomed table?

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#206]
Use case: zoom, summarize, join, then check result.

Should work for both in-memory and database dm-s.

**Comment by krlmlr** [comment]
`pull_tbl()`, with methods for `dm` and `zoomed_dm`?

**Comment by TSchiefer** [comment]
No prefix, cause it would work with both `dm` and `zoomed_dm`? 

And `pull_tbl.dm()` would be the same as `tbl.dm()` currently is?

**Comment by krlmlr** [comment]
No prefix, because it is a known dplyr verb but augmented to work with dm instead of table (hence the `tbl` suffix).

Yes, except `pull()` accepts unquoted names.

**Comment by TSchiefer** [comment]
Sounds good, and I assume we'd keep `tbl.dm()` anyway? 

What about `tbl.zoomed_dm()` (just with one argument then)?

**Comment by krlmlr** [comment]
Let's keep throwing an error in `tbl.zoomed_dm()`.

**Comment by krlmlr** [comment]
Let's also think about `as.list.dm()` and `as.list.zoomed_dm()`.

**Comment by TSchiefer** [comment]
- [ ] Implement `pull_tbl` (both methods)
- [ ] Mention `pull_tbl` in the zoom-vignette

**Comment by TSchiefer** [comment]
`as.list.zoomed_dm()` would give a 1 element list with the zoomed table?

**Comment by krlmlr** [comment]
Yes, we're type-stable. With multi-zoom this will give a list with n elements.
