### ISSUE TITLE
Redefine '[.dm()'?

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#212]
What if `[.dm()` was as an alias for `dm_zoom_to_tbl()`?

**Comment by krlmlr** [comment]
Related to #206. Would it be too bad to phrase `[` or `tbl()` as composition of zoom + pull?

**Comment by TSchiefer** [comment]
Phrase in documentation or implementation?

Also, what should `[.dm()` do in your opinion? Currently `[[.dm()` and `tbl.dm()` do the same thing.

**Comment by krlmlr** [comment]
Documentation only, it's overkill to zoom only to extract tables later on.

`[` should be more like `dm_select_tbl()`, `[[` is a composition of zoom (one table) + pull.

**Comment by TSchiefer** [comment]
So am I understanding correctly, that you'd like to keep the behavior of `[` as it currently is? If that is the case, then I don't understand, why you added this issue to the milestone?

Ok, so in the vignettes we should write, that `[[` and `tbl.dm()` is like `dm_zoom_to_tbl() %>% pull_tbl.zoomed_dm()`, or for that matter like `pull_tbl.dm(dm, table)`?

**Comment by krlmlr** [comment]
Yes, `[` is fine.

We can mention `pull()` in the "zoomed" vignette.

**Comment by TSchiefer** [comment]
Closing this issue since it won't be implemented
