### ISSUE TITLE
Detect duplication of PK and FK

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#214]
Currently the behavior is like this:
``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
dm_nycflights13(cycle = FALSE) %>% 
  dm_add_fk(flights, origin, airports) %>% 
  dm_get_fk(flights, airports)
#> [1] "origin" "origin"
```

<sup>Created on 2019-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
We should detect duplication and warn. We might keep foreign keys in more cases (#225), users might add FKs manually to work around.

**Comment by krlmlr** [comment]
Same for primary keys, I think we allow silent updates?
