### ISSUE TITLE
Remove some examine_ functions

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#238]
because they throw an error.

If a function returns invisibly and throws an error, it should be named `check_*()`.

- [x] `check_cardinality_*_*()` (but keep `examine_cardinality()`)
- [x] `check_if_subset()` (inconsistent name, maybe `check_subset()`)?
- [x] `check_key()`

**Comment by TSchiefer** [comment]
also did `examine_set_equality` -> `check_set_equality` and updated the function-naming-vignette in #240
