### ISSUE TITLE
Prepare dm_examine_constaints() for compound keys

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#239]
Only for the interface, let's not change internals for now.

Should return `vctrs::list_of()`, create with:

```r
new_keys <- function(x) {
  vctrs::new_list_of(x, character())
}
```

- [x] `dm_examine_constraints()` should return a list in the `column` column. Can we keep `dm_check_constraints()` as is?
- [x] `dm_get_all_?ks()`
- [x] `dm_enum_?k_candidates()`
- [x] `enum_?k_candidates()`
- [x] `dm_get_pk()` et al.: Adapt documentation to describe that multiple key columns may be possible, perhaps a short vignette?

**Comment by TSchiefer** [comment]
Just as an aside, have you ever encountered this phenomenon? (this is with the current `dm` version of branch https://github.com/krlmlr/dm/tree/f-239-compound, so `columns` is a list)

``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tibble)
library(testthat)

dm_test <- dm(t1 = tibble(a = 1), t2 = tibble(b = 1))

obj_1 <- dm_examine_constraints(dm_test)
obj_1
#> # A tibble: 0 x 6
#> # … with 6 variables: table <chr>, kind <chr>, columns <list<chr>>,
#> #   ref_table <chr>, is_key <lgl>, problem <chr>
obj_2 <- obj_1

expect_equal(
  obj_1,
  obj_2
)
#> Error: Can't join on 'columns' x 'columns' because of incompatible types (vctrs_list_of/vctrs_vctr/list / vctrs_list_of/vctrs_vctr/list)

expect_identical(
  obj_1,
  obj_2
)
```

<sup>Created on 2020-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TSchiefer** [comment]
>     `dm_get_pk()` et al.: Adapt documentation to describe that multiple key columns may be possible, perhaps a short vignette?
I would say, let's just document it in the Roxygen part of `dm_get_pk()` and `dm_get_fk()` and let's worry about describing the work with compound keys, when we are introducing them. Would that be ok?
