### ISSUE TITLE
dm_draw() not shown

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#251]
in pkgdown examples: https://krlmlr.github.io/dm/reference/dm_draw.html

**Comment by TSchiefer** [comment]
I somehow have the feeling it's related to the fact, that we're creating html and not a regular plot. Is htere an example for something that's displayed both in RStudio's Viewer pane and at the same time in the examples on the pkgdown-site?

**Comment by krlmlr** [comment]
CC @rich-iannone

**Comment by krlmlr** [comment]
There's a history behind this:

- https://github.com/r-lib/pkgdown/pull/960: an implementation that uses {repr}
- https://github.com/r-lib/pkgdown/issues/959: discussion
- https://github.com/r-lib/pkgdown/pull/941: an alternative proposal for using `knit_print()`, slightly outdated
- https://github.com/r-lib/pkgdown/issues/935: discussion
- https://github.com/r-lib/pkgdown/pull/742: an outdated implementation for htmlwidgets 
- https://github.com/r-lib/pkgdown/issues/617: the original issue

I think we need to do more work for seamless conversion to SVG first, and then ensure that a custom output routine is used when rendering the examples, perhaps using a pkgdown fork for now.
