### ISSUE TITLE
Use quo_select_table()

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#257]
and add `quo_rename_table()`, instead of `vars_select()`, `eval_select()` and `vars_rename()`.

**Comment by TSchiefer** [comment]
I have a question regarding negative selections using the new structure.
In the following reprex I would hope to reach the same result for the columns as when using `select()`, but I don't. Is this mix of negative and positive selection something that we should not allow? But even two negative selections would only work if the intersection of the two resulting vectors was used, an approach that can't be generalized, since usually we want rather something like the union. How should we handle this case?

``` r
suppressPackageStartupMessages(
  {library(dm)
   library(tibble)
   library(rlang)
   library(purrr)}
)
mtcars_tibble <- tibble(mtcars)

select(mtcars_tibble, cyl, -mpg, drat, -gear)
#> # A tibble: 32 x 2
#>      cyl  drat
#>    <dbl> <dbl>
#>  1     6  3.9 
#>  2     6  3.9 
#>  3     4  3.85
#>  4     6  3.08
#>  5     8  3.15
#>  6     6  2.76
#>  7     8  3.21
#>  8     4  3.69
#>  9     4  3.92
#> 10     6  3.92
#> # … with 22 more rows

quos <- exprs(cyl, -mpg, drat, -gear)
map(quos, dm:::quo_select_table, colnames(mtcars_tibble))
#> [[1]]
#>   cyl 
#> "cyl" 
#> 
#> [[2]]
#>    cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb 
#>  "cyl" "disp"   "hp" "drat"   "wt" "qsec"   "vs"   "am" "gear" "carb" 
#> 
#> [[3]]
#>   drat 
#> "drat" 
#> 
#> [[4]]
#>    mpg    cyl   disp     hp   drat     wt   qsec     vs     am   carb 
#>  "mpg"  "cyl" "disp"   "hp" "drat"   "wt" "qsec"   "vs"   "am" "carb"
```

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TSchiefer** [comment]
Wouldn't the function `quos_select_tables()` in the following reprex be a more general solution (at least currently, as long as we still have `tidyselect::vars_select()`)?
``` r
suppressPackageStartupMessages(
  {library(dm)
   library(tibble)
   library(rlang)
   library(purrr)}
)
mtcars_tibble <- tibble(mtcars)

quos <- exprs(cyl, -mpg, drat, -gear)
dm:::quos_select_tables(quos, colnames(mtcars_tibble))
#>    cyl   drat 
#>  "cyl" "drat"
map(quos, dm:::quo_select_table, colnames(mtcars_tibble))
#> [[1]]
#>   cyl 
#> "cyl" 
#> 
#> [[2]]
#>    cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb 
#>  "cyl" "disp"   "hp" "drat"   "wt" "qsec"   "vs"   "am" "gear" "carb" 
#> 
#> [[3]]
#>   drat 
#> "drat" 
#> 
#> [[4]]
#>    mpg    cyl   disp     hp   drat     wt   qsec     vs     am   carb 
#>  "mpg"  "cyl" "disp"   "hp" "drat"   "wt" "qsec"   "vs"   "am" "carb"

# with
quos_select_tables <- function(quos, table_names) {
  indexes <- tryCatch(
    eval_tidy(quo(tidyselect::vars_select(table_names, !!!quos))),
    vctrs_error_subscript = function(cnd) {
      # https://github.com/r-lib/vctrs/issues/786
      cnd$subscript_elt <- "element"
      cnd_signal(cnd)
    }
  )
  
  indexes
}
```

<sup>Created on 2020-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
I adapted {dm} to rely on tidyselect 0.2.5 to allow for a faster CRAN release. Let's wait a bit here.

**Comment by krlmlr** [comment]
tidyselect 1.0.0 is now on CRAN, this means we should adapt before releasing.

I think this is the intended usage:

``` r
library(dm)

quo <- rlang::quo(c(cyl, -mpg, drat, -gear))
dm:::quo_select_table(quo, colnames(mtcars))
#>    cyl   drat 
#>  "cyl" "drat"
```

<sup>Created on 2020-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We need `quo(c(...))` to capture the ellipsis: https://github.com/tidyverse/dplyr/blob/master/R/select.R#L109.

**Comment by TSchiefer** [comment]
Right, I noticed the new `dplyr::select()` implementation as well.

So just to be clear:
1. We want to leave the implementation of `dm:::quo_select_table()` as it is
2. We want to have a `tidyselect`-version dependency of "0.2.5"
3. We call `dm:::quo_select_table()` with a `quo` like you mentioned above

Is that right?

**Comment by TSchiefer** [comment]
Nevermind my last comment, just saw your latest commits
