### ISSUE TITLE
Zooming and unzooming is expensive

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#266]
``` r
library(dm)
#> 
#> Attaching package: 'dm'
#> The following object is masked from 'package:stats':
#> 
#>     filter

bench::mark(dm_select(dm_nycflights13(), flights))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                              min median `itr/sec` mem_alloc
#>   <bch:expr>                            <bch> <bch:>     <dbl> <bch:byt>
#> 1 dm_select(dm_nycflights13(), flights) 203ms  227ms      4.49     147MB
#> # … with 1 more variable: `gc/sec` <dbl>
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Profiling shows that >90% of the time is used by zooming and unzooming. 

Collection of primary and especially foreign keys is expensive. Do we really need to collect all keys beforehand and store them redundantly? Would it be sufficient to keep track of the valid columns instead?

- The tracker starts with `set_names(names(data))`; this is a map from old names to new names
- If a column is removed with `select(-...)`, or mutated, we remove it from the tracker
- If a column is renamed, we rename it in our tracker
- We also track if an operation that repeats rows is applied to our data -- if yes, the primary key is invalidated
- When unzooming, we collect the information and only update the primary keys if anything changed

What am I missing?

**Comment by TSchiefer** [comment]
As far as I know we already do this.
The only thing that we could do is to try to get the outgoing FKs in a more efficient way than:
```r
fks <- dm_get_all_fks_impl(dm) %>%
    filter(child_table == table_name) %>%
    pull(child_fk_cols)
```
Problem is that in `def` we store the incoming foreign keys along with each table.

**Comment by krlmlr** [comment]
Why do we collect the outgoing FKs when zooming?

**Comment by TSchiefer** [comment]
Because the column names might change. When inserting or updating the zoomed tibble we need to know which columns are FKs pointing outwards

**Comment by krlmlr** [comment]
Can we keep new and old names, and not collect PKs and FKs when zooming?

**Comment by TSchiefer** [comment]
Maybe, but then we'd need to track all colnames which could also add up(?).

Do we know in which function(s)/at which point(s) we lose most time? Is collecting the PK and outgoing FKs really so expensive? If yes, this is an operation that we need in a lot of places, so it might be worth investing time to optimize it(?)

**Comment by krlmlr** [comment]
Collecting keys needs multiple `unnest()` operations which aren't exactly fast. It consumes more than 90% of the `dm_select()` call in our reprex. Can you confirm with `profvis::profvis(...)`?

Copying a vector of names without modification is cheap. Modifying a longer vector might be slightly more expensive, but collecting appears to be much much more expensive. Also, we don't need to collect keys at all if we know that the existing columns haven't changed.

I'm positive that we should do the minimum amount of work necessary for zooming.

**Comment by TSchiefer** [comment]
> Also, we don't need to collect keys at all if we know that the existing columns haven't changed.

That is a very good point. I will do it this way in that case.

**Comment by TSchiefer** [comment]
Seems to be paying off, at least for the given example:
``` r
# currently I have branch "f-new-zoomed-tracking" installed
suppressPackageStartupMessages(library(dm))
bench::mark(dm_select(dm_nycflights13(), flights)) 
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                              min median `itr/sec` mem_alloc
#>   <bch:expr>                            <bch> <bch:>     <dbl> <bch:byt>
#> 1 dm_select(dm_nycflights13(), flights) 210ms  211ms      4.69     146MB
#> # … with 1 more variable: `gc/sec` <dbl>
```

<sup>Created on 2020-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
# now with github/master:
suppressPackageStartupMessages(library(dm))
bench::mark(dm_select(dm_nycflights13(), flights))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                              min median `itr/sec` mem_alloc
#>   <bch:expr>                            <bch> <bch:>     <dbl> <bch:byt>
#> 1 dm_select(dm_nycflights13(), flights) 269ms  272ms      3.67     146MB
#> # … with 1 more variable: `gc/sec` <dbl>
```

<sup>Created on 2020-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Thanks! Now seeing (with a better reprex):

``` r
library(dm)

dm <- dm_nycflights13()
bench::mark(dm_rename(dm, flights))
#> # A tibble: 1 x 6
#>   expression                  min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>             <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 dm_rename(dm, flights)     35ms   35.3ms      28.4     276KB     85.1
```

<sup>Created on 2020-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
