### ISSUE TITLE
revert destructive CI-Commit

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#267]
The Auto-Commit: https://github.com/krlmlr/dm/commit/86078d622f1b8d3f27660748be47750b170671cb is bugged and I am not sure what causes it. Basically {dm} cannot even be installed in the current state.

**Comment by krlmlr** [comment]
Tried to revert, let's wait for the build.

I suspect this is caused by styler: https://travis-ci.org/krlmlr/dm/jobs/646859095#L941.

**Comment by lorenzwalthert** [comment]
OMG! Is that dev styler or the CRAN release?

**Comment by krlmlr** [comment]
dev, only happens since today I think.

**Comment by lorenzwalthert** [comment]
Its related to the new caching feature I think. https://github.com/r-lib/styler/pull/578. Investigating. This is a big thing. Thanks for reporting!

**Comment by lorenzwalthert** [comment]
It's resolved. I successfully styled {dm} with the devel version of styler. Should we turn on styler support again?

**Comment by lorenzwalthert** [comment]
All things resolve in CRAN version `v1.3.2`.
