### ISSUE TITLE
difference in behavior `copy_to.dm()` & `dm_add_tbl()`

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#322]
For a local `dm`, `copy_to.dm()` converts a `data.frame` to a `tbl` but `dm_add_tbl()` doesn't.

This is caused by the call in `copy_to.dm()`:
```r
df <- copy_to(dm_get_src(dest), df, unique_db_table_name(name), temporary = temporary, ...)
```
because `dplyr:::copy_to.src_local()` calls `tbl(dest, name)`.

The asymmetry does not occur for remote `src`.

Not sure if this is worth pursuing.

**Comment by TSchiefer** [comment]
I assume this is just a problem if you want to add a **local** `data.frame` to a **local** `dm`.
In this case most people probably would not think of using `copy_to.dm()` in the first place(?)

**Comment by krlmlr** [comment]
Not sure we should enforce tibbles in dm objects.
