### ISSUE TITLE
set key constraints on PG fails...

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#330]
when one of the tables has a name of the form "x.y" (x, y anything, the "." is the problem, cause I presume PG expects a schema.table-type of addressing)

This can potentially be solved by generally creating queries like:
```sql
'ALTER TABLE iris_2_2020_04_22_18_00_53_2 ADD FOREIGN KEY ("iris_2.key") REFERENCES iris_1_2020_04_22_18_00_53_1(key) ON DELETE CASCADE ON UPDATE CASCADE'
```
(wrapping the table names in quotes)

**Comment by krlmlr** [comment]
Solved in 7c4ade6.
