### ISSUE TITLE
tidyselect nothing locally vs. remotely

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#360]
It might be tricky to implement selecting no columns with a tidyselect-helper in an equivalent manner remotely as it is done locally.

In any case we should deal with this case consistently (e.g. in `check_key()`), independent if it's a remote or local table.

``` r
packageVersion("tidyselect")
#> [1] '1.1.0'
library(tidyselect)
library(tibble)


# if my_test_src() is MSSQL
devtools::load_all("~/git/cynkra/dm")
#> Loading dm
#> 
#> Attaching package: 'testthat'
#> The following object is masked from 'package:tidyselect':
#> 
#>     matches
#> Testing on mssql

mtcars_mssql <- copy_to(my_test_src(), tibble(mtcars), name = "mtcars")
#> Created a temporary table named: #mtcars

# locally
select(tibble(mtcars), starts_with("zzz"))
#> # A tibble: 32 x 0

# remotely
select(mtcars_mssql, starts_with("zzz"))
#> Error: length(select) not greater than 0L
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
SQL can't have zero columns in an expression, each key must have at least one column. Do we need a clean error message?

**Comment by krlmlr** [comment]
Not sure what to do here, this feels out of scope.
