### ISSUE TITLE
dm_from_src() MS SQL Server

### ISSUE THREAD

**Issue by jnsger** [krlmlr/dm#367]
Hi

I'm trying to import a database from our server, but get the error below.

`dw_dm <- dm_from_src(conn, learn_keys = TRUE)`

`Error: nanodbc/nanodbc.cpp:1617: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'AdditionalFundingRequestsFact'.  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. 
<SQL> 'SELECT *
FROM AdditionalFundingRequestsFact AS "zzz15"
WHERE (0 = 1)'`

The table in question definitely exists (I can locate it and extract using `tbl() %>% collect()` just fine).
There are a number of different schema in the database, but it's the very first table in the database alphabetically.

Our server is running:
MSS version: 12.00.4416
R version: 4.0.0

**Comment by krlmlr** [comment]
Thanks. This is a current limitation, does `learn_keys = FALSE` work?

The query is defined in `mssql_learn_query()`  -- the Postgres variant already supports a `schema` argument, maybe we could support it for SQL Server too?

**Comment by jnsger** [comment]
Set `learn_keys =FALSE` got some progress actually, but still gave this error:

> Warning message:
> Table(s) `IMInvestigationEnrolmentChanges`, `IMInvestigationEnrolmentChanges_20160902`, `PaymentData`, `RefundSchedule`, `VosReceived`, ... (976 total) cannot be accessed.
> i Use `tbl(src, ...)` to troubleshoot.
> i Set the `table_name` argument to avoid this warning.

It seems to be only pulling tables from a single schema.

Setting the table name didn't help either, all the tables specified couldn't be accessed, even though they are accessible directly through `tbl() %>% collect()`

**Comment by jnsger** [comment]
Yeah it seems to be pulling from the first schema only, then blocks the rest.

A schema argument could help with this.

**Comment by krlmlr** [comment]
For now you can work around with creating the dm manually, as described in https://krlmlr.github.io/dm/articles/dm-db.html#building-a-dm-from-tables-1.

Fixing this limitation will take some ground work.

**Comment by jnsger** [comment]
Ah yes, great, will check that out, thanks.

**Comment by dewoller** [comment]
> For now you can work around with creating the dm manually, as described in https://krlmlr.github.io/dm/articles/dm-db.html#building-a-dm-from-tables-1.

Great package!!  Fills a great need.  This link is broken.

**Comment by krlmlr** [comment]
Thanks! Updated link: https://krlmlr.github.io/dm/articles/howto-dm-db.html.
