### ISSUE TITLE
Avoid src_sqlite() everywhere

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#372]
- [ ] examples
- [x] vignettes
- [x] tests

Deprecated in dplyr 1.0.0.

Related: https://github.com/krlmlr/dm/issues/336.

**Comment by krlmlr** [comment]
Examples handled in https://github.com/krlmlr/dm/pull/364, they will have to wait. Tests will be fixed as we refactor.

**Comment by krlmlr** [comment]
Leaving the issue open so that we can double-check later.

**Comment by TSchiefer** [comment]
Could you please give me an update what to do here? First work on #364?
