### ISSUE TITLE
Improve GHA workflow

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#374]
- [x] By default, only SQLite is tested -- no database needs to be installed for most jobs. For the database tests, I'd prefer one job per database, and install only that database for each job, like dbplyr does. (It's handled differently on Travis, we can do better here.) The `DM_TEST_SRC` environment variable specifies which database to test against, for the database tests set this and `TIC_ONLY_TESTS`. See also `./Makefile`.
- [x] Add the MSSQL setup from the odbc or dbplyr tests
- [ ] ~~Test R-devel on Linux instead of macOS~~
- [ ] ~~Only test macOS for R-release~~
- [x] Add one R-release job for Windows
- [x] Remove LaTeX for all but one runner
- [x] Reenable R 3.3
- [ ] ~~Can we do the same that tidyverse does for installing packages on Linux?~~

Consider multiple `.yml` files?

Follow-up to #369.

**Comment by krlmlr** [comment]
GHA doesn't support "continue-on-error": https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033.

**Comment by pat-s** [comment]
> Test R-devel on Linux instead of macOS

No installer [yet available](https://github.com/r-lib/actions/issues/49) for R-devel on Linux.

**Comment by krlmlr** [comment]
We can't do a full macOS matrix, we only have binaries for R-release and R-oldrel :-( The current matrix looks fine.

**Comment by krlmlr** [comment]
I wonder why we keep getting rate limitation errors, e.g. https://github.com/krlmlr/dm/runs/711756871#step:17:5487.

**Comment by pat-s** [comment]
> I wonder why we keep getting rate limitation errors, e.g. krlmlr/dm/runs/711756871#step:17:5487.

Interesting. {tic} sets a GITHUB_PAT specifically, using the GITHUB_TOKEN that comes with every build.

Haven't seen this in any other repo yet.

> Using github PAT from envvar GITHUB_PAT

**Comment by krlmlr** [comment]
I suspect installing all dev versions is costly in terms of API calls. Should we do this only for the master branch?

**Comment by pat-s** [comment]
Package caching happens on a daily base, branch-agnostic. Even PRs use the same cache: https://github.com/krlmlr/dm/runs/746934046

Hence, the installation is only happening once a day, no matter which scenario.

So I'd say it's fine as it is?

**Comment by krlmlr** [comment]
If one CI run consumes 100 out of 1000 API requests, we'll be running into limitations fairly frequently. We could supply our own secret too, that would bump the limitation to 5000 calls I guess?

https://github.com/krlmlr/dm/runs/747497149#step:18:36 suggests that GitHub is still probed with every run. This still consumes API calls even if the package hasn't changed.

**Comment by pat-s** [comment]
Ah just seeing the `step_run_code(print(gh::gh("/rate_limit")))` now.

And yes, it seems that the rate is decreased even if packages are not being installed. The query is still executed in the background, consuming the calls.

AFAICS one run consumes ~50 requests and ~100 when branch+PR is being run (I guess that's where your 100 comes from?)

Not sure if a secret bumps to 5k. I'll test quickly.

**Comment by pat-s** [comment]
Both odbc and dbplyr use `services:` which [only work on Linux runners](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices).

Should I explore on my own how to get these running on macOS and Windows or should we stick to Linux only tests for these two DB for now?

**Comment by krlmlr** [comment]
DB tests on Linux only is fine for now.

**Comment by krlmlr** [comment]
Works now.?
