### ISSUE TITLE
Don't print table source

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#386]
if the dm doesn't have tables.

Reference: #385.

**Comment by TSchiefer** [comment]
Should `dm_get_src(dm())` still return `default_local_src()` (currently `.GlobalEnv`), or wouldn't it be more consistent to return `NULL`, more in line with the change in this issue?

**Comment by krlmlr** [comment]
Not sure. Let's discuss this in a separate issue.

**Comment by TSchiefer** [comment]
Ok, just asked cause the implementation of `print.dm()` would be more straightforward for that corner case if we changed that.
