### ISSUE TITLE
update doc of 'dm_update_zoomed()'

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#403]
...or adapt implementation.

From the documentation: `dm_update_zoomed() overwrites the originally zoomed table with the manipulated table. The filter conditions for the zoomed table are added to the original filter conditions.`

Behavior:
``` r
suppressPackageStartupMessages({
  library(dm)
  library(tibble)
  library(dplyr)
})
dm(t1 = tibble(a = 1:10)) %>% 
  dm_zoom_to(t1) %>% 
  filter(a > 5) %>% 
  dm_update_zoomed() %>% 
  dm:::get_filter_for_table("t1")
#> # A tibble: 0 x 2
#> # … with 2 variables: filter_expr <list>, zoomed <lgl>

# if there already was a filter condition beforehand, it stays:
test <- dm(t1 = tibble(a = 1:10)) %>% 
  dm_filter(t1, a < 7) %>% 
  dm_zoom_to(t1) %>% 
  filter(a > 5) %>% 
  dm_update_zoomed() %>% 
  dm:::get_filter_for_table("t1")
test
#> # A tibble: 1 x 2
#>   filter_expr  zoomed
#>   <named list> <lgl> 
#> 1 <language>   FALSE
test$filter_expr
#> [[1]]
#> a < 7
```

<sup>Created on 2020-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
No longer relevant if filter expressions are going away (#426), need to skim all documentation for `"[Ff]ilter"`.
