### ISSUE TITLE
'copy_dm_to()' to schema

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#432]
cf. https://github.com/krlmlr/dm/pull/428#issuecomment-666305219 and af980c2 (this failed for both MSSQL and Postgres)

For me it seems the right way to provide an additional argument `schema`, that will make it clear, that this should be quoted independently of the `table_name`. 
But I am open to other ideas.

**Comment by krlmlr** [comment]
Should we solve this with schema helpers for now? These could be used in the `table_name` argument.

**Comment by TSchiefer** [comment]
Having trouble thinking of a user-friendly API here. Would you have an example how you'd like it to look?
