### ISSUE TITLE
Error creating dm from Source

### ISSUE THREAD

**Issue by asimumba** [krlmlr/dm#440]
Hi, 
 I am exploring the usage of the dm package to test out the relational model for my database. But I have the following error.
`> my_dm <- dm_from_src(con)
Error: nanodbc/nanodbc.cpp:1617: 00000: [FreeTDS][SQL Server]Invalid object name 'BA_Demo'.  [FreeTDS][SQL Server]Statement(s) could not be prepared.`

A bit of context, this happens when I try to connect using dplyr's `tbl` without using the `in_schema` set.

The following works to return a tibble.
`data <- con %>%
  tbl(dbplyr::in_schema("shema","table"))`

The constraint is that I cannot create a dm object with the entire database.

**Comment by krlmlr** [comment]
Thanks. Can you please try the GitHub version with the `schema` argument to `dm_from_src()`?

**Comment by asimumba** [comment]
Thank you @krlmlr. The Github version worked like magic even without supplying the schema argument `my_dm <- dm::dm_from_src(con, learn_keys = TRUE)`.

Awesome  package I must mention.

**Comment by asimumba** [comment]
@krlmlr I came across this in the help documentation for `dm_from_src` - `For MSSQL databases schema (default: "dbo") is supported.` Does this mean in the case where the schema used is other than dbo, then the tables cannot be accessed? I have realised for my database, `dbo` does not house the tables I need.

**Comment by krlmlr** [comment]
It should perhaps read "For MSSQL databases, the `schema` argument (default: `"dbo"`) is supported.". Would you like to submit a documentation PR?
