### ISSUE TITLE
Handling of filter conditions for `cdm_get_tables()`

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#63]
Currently ignores filter conditions. When using `cdm_get_tables()` while filter conditions are set we should do one of:
1. give a warning message
1. throw an error
1. return the filtered tables

In the third case (which I think is the approach we should probably chose) we would need to have a new function that's implemented like `cdm_get_tables()` currently is, and use it wherever possible, because in many places we just need for example the column names and we don't care about filters being applied or not.

**Comment by krlmlr** [comment]
I think this is fine -- `cdm_get_tables()` is a low-level operation that returns the raw tables. We should document this properly, though.

**Comment by TSchiefer** [comment]
What about proper documentation and a little warning in case of set filter conditions? (don't have a strong opinion, if you just want doc, it's fine)

**Comment by krlmlr** [comment]
This is currently used internally in lots of places. Let's reconsider after #54.

**Comment by krlmlr** [comment]
Filters are now handled transparently, no need to take action.
