### ISSUE TITLE
function `cdm_reset_filter()`

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#64]
This function would remove either all filters, or better, it let's you remove the n-th filter, cause you made a typo there, and you don't want to remove all filters at once because the rest seems fine. Maybe two different functions for those two scenarios?

**Comment by krlmlr** [comment]
This seems similar to requesting an `unfilter()` operation on dbplyr tables -- it might be possible, but then wo could always use the original object before applying the filter. This is easy if we always use a new name for derived objects.

**Comment by TSchiefer** [comment]
I implemented `cdm_reset_all_filters()` it in #66 for internal use - it was nice to have for `cdm_flatten_to_tbl()` and might be useful later on as well. But I guess I agree, we do not necessarily need it exported.
