### ISSUE TITLE
Redesign constructors and validators

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#69]
- `dm()` should be replaced by logic to extract pk/fk information from a datamodelr object
- `new_dm()` becomes `dm()`, no longer accepts datamodelr object
- `new_dm2()` becomes `new_dm()` -- a thin wrapper around `tibble()` after #57. Need to revisit interface carefully. Maybe extract `patch_dm()` to update parts of an existing dm?

**Comment by krlmlr** [comment]
Do we need to do anything else here?

**Comment by TSchiefer** [comment]
Extended `validate_dm()` coming up
