### ISSUE TITLE
Define filtering operation

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#70]
- referential integrity of the result guaranteed
- filter then flatten is the same as flatten with inner join then filter (?)

In the documentation in `?cdm_filter` and `vignette("dm-filtering")` .

**Comment by TSchiefer** [comment]
Hmm, actually, if we promise referential integrity of a connected component containing at least one filtered table, we might need to revisit `tbl.dm()`: so far it only takes into account the tables that are filtered AND/OR are on the way from a filtered table to the requested table.

But what happens, if we have a faulty foreign key relation between one of the tables that are neither filtered nor on the way from a filtered table to the requested table? Basically, the result might have too many rows, if we have a "bad" (lacking referential integrity) `dm`.

We could implement it similarly to my hack in https://github.com/krlmlr/dm/pull/71/commits/22a7638dd31d8414dc68d2340ca9e6241fe9aa28 (set all other filters in the connected component to `TRUE`; in our case here, apart from the ones that have already a set filter condition)

**Comment by krlmlr** [comment]
Before proceeding, can you please construct an example?

**Comment by TSchiefer** [comment]
``` r
suppressPackageStartupMessages(library(tidyverse))
library(dm)

tbl_1 <- tibble(a = 1:5, b = 1:5)
tbl_2 <- tibble(c = 1:2)
tbl_3 <- tibble(d = 2:4)

bad_dm <- as_dm(list(
  tbl_1 = tbl_1, tbl_2 = tbl_2, tbl_3 = tbl_3)) %>% 
  cdm_add_pk(tbl_2, c) %>% cdm_add_pk(tbl_3, d) %>% 
  cdm_add_fk(tbl_1, a, tbl_2) %>% cdm_add_fk(tbl_1, b, tbl_3)
# mind that `tbl_2` has 2 rows and `tbl_3` has 3 rows

cdm_draw(bad_dm)
```

![](https://i.imgur.com/pO8HgbY.png)

``` r

# without filtering we get:
tbl(bad_dm, "tbl_1")
#> # A tibble: 5 x 2
#>       a     b
#>   <int> <int>
#> 1     1     1
#> 2     2     2
#> 3     3     3
#> 4     4     4
#> 5     5     5

# when filtering `tbl_3`:
tbl(cdm_filter(bad_dm, tbl_3, 1 == 1), "tbl_1")
#> # A tibble: 3 x 2
#>       a     b
#>   <int> <int>
#> 1     2     2
#> 2     3     3
#> 3     4     4

# when filtering both `tbl_2` and `tbl_3`:
tbl(cdm_filter(bad_dm, tbl_3, 1 == 1) %>% cdm_filter(tbl_2, 1 == 1), "tbl_1")
#> # A tibble: 1 x 2
#>       a     b
#>   <int> <int>
#> 1     2     2
```

<sup>Created on 2019-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
I think this only means that we need to revisit our implementation and not override with `left_join` even if filters are set. The remaining parts of the implementation still look correct -- in particular we only need to apply all filters once via `tbl(dm, start)` .

**Comment by krlmlr** [comment]
Filtering also can't guarantee referential integrity, unfortunately.

With right and full outer joins, our current implementation doesn't behave correctly. Need to think about a good solution.
