### ISSUE TITLE
Clarify error message when joining tables with cycles

### ISSUE THREAD

**Issue by gadenbuie** [krlmlr/dm#74]
While working through the README and vignettes to learn this package (it's fantastic by the way, thank you!) I ran into this error:

```r
dm_nycflights <- cdm_nycflights13(cycle = TRUE)

# ... testing and exploration ...

dm_nycflights %>%
  cdm_join_to_tbl(airports, flights, join = semi_join)
## Error: `table` must be a string.
## Call `rlang::last_error()` to see a backtrace
```

It took me a while to figure out that the issue was `cycle = TRUE` and not the format of the table arguments. Finally, I realized the [lines I was supposed to run](https://github.com/krlmlr/dm/blob/3d2885e5df5b0507d9d2b49aad933cf3a071a696/README.Rmd#L223-L224) needed `cycle = FALSE`.

Maybe `cdm_join_to_tbl()` could provide a better hint in this case?

As a related suggestion, the README mentions that `cdm_join_to_tbl()` requires cycle-free relationships, but it might be helpful to explain why this is the case.

**Comment by krlmlr** [comment]
Thanks for raising this. The error messages should look better now. I still need to add tests that these errors actually occur, we didn't have them.

I'd rather sweep under the rug for now and implement better ways for handling cycles, perhaps in #55 ;-) I'm happy to review documentation improvements, though.
