### ISSUE TITLE
Stricter logic for `cdm_flatten_to_tbl()`

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#75]
The function itself should not think too much by itself, it should apply the same logic for all join-methods. Furthermore, only tables that are (direct) parents will be allowed for this function (no grandparents etc.). If the user passes tables in the ellipsis, the joins will happen in this order.

1. `left_join()`, `inner_join()`, `full_join()`: if no tables given in the ellipsis, the result will depend on the order of the tables in the (relevant part of the) `dm`, but it will only affect the column order.
2. `semi_join()`: the result will be exactly those rows, that are referenced by ALL parent tables.
3. `anti_join()`: the result will be those rows, that are NOT referenced by ANY parent table (i.e. referenced by NO parent table). It might be more interesting for the user to have a function telling them, which rows are not referenced by at least one parent table, but that needs to be another function.
4. `nest_join()`: the created columns should have the names of the RHS tables of the join. Again, if ellipsis empty, the order of those tables in the `dm` plays a role for the resulting order of the columns.
5. `right_join()`: if the ellipsis is empty, the number of rows might depend on the table that comes last in the `dm` table list (if no referential integrity is given). In this case, a warning is issued.

There will be a further function `cdm_flatten_deep_to_tbl()`, which works only for `left_join()`, `inner_join()` and `full_join()`, which also allows for deeper table hierarchies (grandparents etc.)

**Comment by krlmlr** [comment]
Sounds good.

Let's exclude `nest_join()` for now.

How about `cdm_stomp_to_tbl()` ?

**Comment by krlmlr** [comment]
For `nest_join()`, pass the name via tidy evaluation. Works for the other join types too.

``` r
library(tidyverse)
library(nycflights13)

nest_join(airlines[1:3, ], flights)
#> Joining, by = "carrier"
#> # A tibble: 3 x 3
#>   carrier name                   flights               
#> * <chr>   <chr>                  <list>                
#> 1 9E      Endeavor Air Inc.      <tibble [18,460 × 18]>
#> 2 AA      American Airlines Inc. <tibble [32,729 × 18]>
#> 3 AS      Alaska Airlines Inc.   <tibble [714 × 18]>

flights_var <- expr(flights)
rlang::eval_tidy(rlang::quo(nest_join(airlines[1:3, ], !!flights_var)))
#> Joining, by = "carrier"
#> # A tibble: 3 x 3
#>   carrier name                   flights               
#> * <chr>   <chr>                  <list>                
#> 1 9E      Endeavor Air Inc.      <tibble [18,460 × 18]>
#> 2 AA      American Airlines Inc. <tibble [32,729 × 18]>
#> 3 AS      Alaska Airlines Inc.   <tibble [714 × 18]>

# Better, but dplyr 0.9.0 only
# https://github.com/tidyverse/dplyr/issues/4571
flights_var <- quo(flights)
rlang::eval_tidy(rlang::quo(nest_join(airlines[1:3, ], !!flights_var)))
#> Joining, by = "carrier"
#> # A tibble: 3 x 3
#>   carrier name                   `~flights`            
#> * <chr>   <chr>                  <list>                
#> 1 9E      Endeavor Air Inc.      <tibble [18,460 × 18]>
#> 2 AA      American Airlines Inc. <tibble [32,729 × 18]>
#> 3 AS      Alaska Airlines Inc.   <tibble [714 × 18]>
```

<sup>Created on 2019-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
@cutterkom: We need to wait for this until investing further in documenting `cdm_flatten_to_tbl()` .

**Comment by TSchiefer** [comment]
It seems to me, that `full_join()`, `right_join()` and `nest_join()` have a problem, if a filter is set: there will be in general too many rows on the RHS tables, if we don't evaluate the filter conditions for them.

My suggestion would be to throw an error and advise the user to use `cdm_apply_filters()` first in those cases.

For `left_join()`, `inner_join()`, `semi_join()` and `anti_join()` I have the impression that it works also with filter conditions, if we use `tbl(dm, start)` to get the start-tibble.

Would you say that is correct, @krlmlr?

**Comment by krlmlr** [comment]
I'm fine removing support for flattening filtered dm-s with joins where our implementation gives the wrong result. Let's add tests for all cases we can think of -- the invariant is that flatten must be the same as apply + flatten (or that an error is given).
