### ISSUE TITLE
Default settings for `cdm_copy_to()`

### ISSUE THREAD

**Issue by TSchiefer** [krlmlr/dm#80]
The default parameters setting for `cdm_copy_to()` should produce temporary tables with `unique_table_names`.

Idea is to have the default `unique_table_names = NULL`, which becomes `TRUE` when `temporary = TRUE` and `FALSE` otherwise.

Could either be fixed in #79 or in a future PR.

**Comment by TSchiefer** [comment]
how about not offering the parameter `unique_table_names` in the first place?

This way, we would just need to check the combination of `temporary` and `table_names`:
1. if `temporary = TRUE`, `table_names` needs to be `NULL`, then unique table names are created, otherwise an error is thrown
2. if `temporary = FALSE`, `table_names` can be either `NULL` (-> unique table names) or a character vector

**Comment by krlmlr** [comment]
`table_names` could also be a function that accepts the original names and returns a character vector of new names.

Let's also consider #23 for the discussion here -- maybe we can solve it on the way?

**Comment by TSchiefer** [comment]
So the default for `cdm_copy_to()` would be `temporary = TRUE` and (a new parameter) `schema = NULL` and (something like) `table_names = repair_table_names_for_db(dm, schema, temporary)`. 

`repair_table_names_for_db()` would -- depending on if temporary or not -- produce different names and in case of permanent tables it would include the schema name within an `Id`-object. But you could still also provide your own choice of names, if you want to override the default.

Do I understand this correctly?
